name: Generate and Deploy Sitemap

on:
  schedule:
    - cron: '30 18 * * *'  # Every day at 00:00 IST
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run sitemap generator
        env:
          STOREFRONT_TOKEN: ${{ secrets.STOREFRONT_TOKEN }}
        run: |
          python sitemap.py

      - name: Commit and push sitemap.xml
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "info@theluxeveill.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/luxeveil/sitemap.git
          git add .
          git commit -m "Update sitemap"
          git push origin HEAD:main
